### ISSUE TITLE
Refactoring: validation flow

### ISSUE THREAD

**Issue by artemeknyazev** [artemeknyazev/generic-api#18]
There are five ways user input can get into the system:
* request body
* query params
* route params
* cookies
* other headers

**TODO:**
- [x] Route params currently are handled only by `acquire*` middlewares. Must ensure validity of ids before using them in the db query
 - [x] Query params are currently not used. Create “soft” validation rules for them — if the value is not in the enum or does not fit to a pattern it is discarded without errors. Actually, is this a valid approach? Maybe handle using “hard” validation to help clients debug issues?
- [x] Request body validation are currently handled by a `validateBody` middleware that uses either schema provided to the middleware or an id of a schema stored in `schemas/validation` directory. This only ensures the presence of required fields and validity of values. The other part of validation is to ensure a consistency of a value with the business rules — see `validateAssignedToMiddleware `
  - [x] Ideally there should be only one call to a middleware that provides request body validation for the route. It first validates values using the validator library, then uses business logic validator. Note, that the latter also is linked to the authorization layer — e.g. can't link a task to a current task from a project user is not participating in
- [x] Cookies are currently not used. Consider the issue again after implementing the client (#16)
- [x] Request headers are currently used only for authentication. Consider the issue later

**Comment by artemeknyazev** [comment]
Query params will be handled in the issue #20. Moving it there

Route params and request body validators are in the PR #22
